
const pageInfo = [
    {
        title: "generate",
        ref: 'generate',
        boxOneTitle: "Variables",
        boxTwoTitle: "Libraries",
        boxOnePrompt: "Create a list of variables for the following: \n\n",
        boxTwoPrompt: "Create a list of libraries for the following: \n\n",
        boxOneDescription: "Variables are the things that you want to change in your code or the things that you want to use in your code.",
        boxTwoDescription: "Libraries are the things that you want to use in your code. For example, you might want to use the math library to do math functions.",
    },
    {
        title: "anything",
        ref: 'anything',
        boxOneTitle: "",
        boxTwoTitle: "",
        boxOnePrompt: "",
        boxTwoPrompt: "",
        boxOneDescription: "",
        boxTwoDescription: "",
    },
    {
        title: "search",
        ref: 'search',
        boxOneTitle: "Citations",
        boxTwoTitle: "Key Searches",
        boxOnePrompt: "Create a list of citations for the following: \n\n",
        boxTwoPrompt: "Create a list of key searches for the following: \n\n",
        boxOneDescription: "Citations are the names of the people who wrote the information that you are using.",
        boxTwoDescription: "Key searches are the things that you want to search for. For example, you might want to search for the word 'cat'.",
    },
    {
        title: "brainstorm",
        ref: 'brainstorm',
        boxOneTitle: "Key Points",
        boxTwoTitle: "Summary",
        boxOnePrompt: "Create a list of key points for the following: \n\n",
        boxTwoPrompt: "Create a summary for the following: \n\n",
        boxOneDescription: "Key points are the things that you want to remember about the topic. For example, you might want to remember that cats are cute.",
        boxTwoDescription: "A summary is a short description of the topic. For example, you might want to write a summary of the topic 'cats'.",
    },
    {
        title: "writer",
        ref: 'generate',
        boxOneTitle: "Keywords",
        boxTwoTitle: "Topics",
        boxOnePrompt: "Enter a list of keywords for the following: \n\n",
        boxTwoPrompt: "Enter a list of topics for the following: \n\n",
        boxOneDescription: "Keywords are the things that you want to search for. For example, you might want to search for the word 'cat'.",
        boxTwoDescription: "Topics are the things that you want to write about. For example, you might want to write about the topic 'cats'.",
    },
]      

export default pageInfo;
